### ISSUE TITLE
update server.xml so that the app can be run remotely

### ISSUE THREAD

**Issue by tam512** [OpenLiberty/guide-security-intro#200]
Currently the _guide-security-intro_ app can only be run locally with `http://localhost:9080`
Is there a reason that we don't want to have `host="*"` in <httpEndpoint .../> as following so that it can be accessed remotely?

```
 <httpEndpoint host="*"
    id="defaultHttpEndpoint"
    httpPort="${http.port}"
    httpsPort="${https.port}" />
```

**Comment by gkwan-ibm** [comment]
We will study. I guess we can add `host="*"` in the `httpEndpoint` configuration

**Comment by gkwan-ibm** [comment]
close
- the server.xml files were updated
