### ISSUE TITLE
Present encoding passwords section in a clear way

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-security-intro#62]
Two users were confused by this section and where to find the `wlp/bin` section because they think they need to run the command or want to try to run the command themselves.

Section that used to be at the end of `Configuring a User Registry`:

### Encoding passwords using securityUtility

It is not recommended to store passwords in plain text. For simplicity reasons, the application in this guide uses XOR encoding to encode the passwords, as you can see in the `userRegistry.xml`. 
For example, to encode 'bobpwd', the Liberty `securityUtility` command can be run from the `wlp/bin` directory from the Liberty application server.

The `securityUtility` command can be run with the parameter `encode` and the provided text to encode:
```
./securityUtility encode --encoding=xor bobpwd

```
This command should produce the following output:
```
{xor}PTA9Lyg7
```

**Comment by yeekangc** [comment]
Upon discussion with @evelinec, an option is to mention the securityUtility in the section where the userRegistry.xml is created.  Add a sentence or two there to explain that the passwords were encoded with the command.  This should avoid confusion where users think they will need to do something with securityUtility and keep things simple and clear.  Something to consider.

**Comment by yeekangc** [comment]
See #56 and #61 for user feedback.

**Comment by justineechen** [comment]
Revised version will not include a sub-header for this section and I will insert this where the userRegistry.xml is created:

It is not recommended to store passwords in plain text. For simplicity reasons, the application in this guide uses XOR encoding to encode the passwords, as you can see in the `userRegistry.xml`. This passwords are encoded using the Liberty `securityUtility` command.
