### ISSUE TITLE
500 Server Error when user is already logged in

### ISSUE THREAD

**Issue by proubatsis** [OpenLiberty/guide-security-intro#70]
The steps to reproduce this issue are the same as the issue found in the JWT guide: https://github.com/OpenLiberty/guide-microprofile-jwt/issues/37

1. Navigate to `http://localhost:9080` on Firefox or Safari (This issue is not present on Chrome)
2. Log in
3. Go back using the browser's navigation features, **do not* use the log out button.
4. Try logging in again with either correct or incorrect credentials
5. Error

![image](https://user-images.githubusercontent.com/8409464/47181391-e0c83000-d2f0-11e8-8083-fd9373430083.png)

**Comment by justineechen** [comment]
Findings: 
- If you refresh the page at the log in page after using the back button it redirects you to the logout button
- After hitting the error page, the user can change the url to localhost:9080 once again and still be able to reach the logout button (It is not necessary to completely start/stop the server again to continue using the application)

Possible solutions:
- Redirect the back button so that it does not show the login page
- Have a custom back button that redirects to a home page where the user is logged in (User can still hit the browser back button)

**Comment by proubatsis** [comment]
The second solution you mention a `custom back button`. Does that mean putting a back button on the page itself? I don't think that's a valid solution because you can't ignore that the browser's navigation buttons exist and can be used.

The first option is something to evaluate, but I don't know that this would necessarily be ideal either since going to a different page would be unexpected behaviour from the user's point of view.

Maybe you could display a message if they try to login again stating that they are already logged in and must logout first? This would be still be an "error" message I guess, but it's more clear than seeing an internal server error. Maybe there are better ways to solve this? This is just my first thought that comes to mind.

**Comment by justineechen** [comment]
After implementing the same filter from the JWT-guide, the behavior of the application is:
On Safari:
1. Navigate to localhost:9080 and log in
2. Use the browser's back button
3. Page refreshes and shows the same logged in user
4. Use the browser's back button
5. Returns to whichever page browser was on before going to localhost:9080 

- 

1. Navigate to localhost:9080 and log in
2. Log in
3. Log out
4. Log in as a different user
5. Use the browser's back button
6. Page refreshes and shows the same user
7. User the browser's back button
8. Either 403 Unauthorized OR it will show the information/application of the user that is currently logged in 

I haven't seen the previous exception yet but am still testing.

**Comment by evelinec** [comment]
- testing the fixes today
