### ISSUE TITLE
Post test issues on multipane

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-security-intro#80]
- [ ] The src/main/webapp/WEB-INF/web.xml file contains the rest of the security declaration for the application. => the hotspot is pointing to section of the web.xml file instead of the whole file. 
- [ ] The server.xml file contains the security configuration of the server. => similarly here
- [ ] The `http://localhost:9080` url is not working on FF, even for singlepane. OK on chrome.

**Comment by gkwan-ibm** [comment]
Regarding `The http://localhost:9080 url ...`, would you retry by clean the cookie/history or use private browser?

**Comment by gkwan-ibm** [comment]
>     The src/main/webapp/WEB-INF/web.xml file contains the rest of the security declaration for the application. => the hotspot is pointing to section of the web.xml file instead of the whole file.

The hotspot is pointing to a section. It looks fine to me. If the hotspot at "the security declaration" phrase, it will be displayed at `the security declaration`.

**Comment by gkwan-ibm** [comment]
@evelinec if not agree, please suggest how to hotspot the security configuration section in web.xml and server.xml

**Comment by evelinec** [comment]
I tested opening the URL on a private windows on FF, and it's working. Not sure we need to make that clear somewhere for this guide. 

The two hotspot issues are the similar situations I brought up to discuss last time. Looks like it's minor that it's ok as it is. 

I'm good to close this issue.
