### ISSUE TITLE
Need to add "security" to page-tag

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-security-intro#82]
Currently having `:page-tags: [Java EE']`, need to add "security" to it.

**Comment by gkwan-ibm** [comment]
Currently, we only allow the following tags
- Micro Profile
- Maven
- Docker
-  Kubernetes
- Gradle
- Java EE

If adding security for searching, it will be done by https://github.com/OpenLiberty/guides-common/issues/234 to use `:page-search-keywords:`

**Comment by evelinec** [comment]
This issue has not been fixed yet. The `security` tag isn't being added in the readme.adoc.

**Comment by evelinec** [comment]
@wojtczat can you create another PR for the `qa` branch? Thanks.

**Comment by gkwan-ibm** [comment]
I assume the "security" is for searching, it should be add to `:page-search-keywords:`

**Comment by evelinec** [comment]
@gkwan-ibm According to the latest list of allowed tags from the UI team (see here https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid), security is one of them.

**Comment by evelinec** [comment]
@wojtczat don't want to trouble you. We'll sort this out and resolve it. Thank you for your help.

**Comment by evelinec** [comment]
Fixed in #85

**Comment by evelinec** [comment]
Verified that on the ol.io site, we can search for this guide now.
