### ISSUE TITLE
Readme content review

### ISSUE THREAD

**Issue by jonathanxue** [OpenLiberty/guide-security-intro#98]
## Adding authentication and authorization
* `which is why an HTTP connection from a browser will be switched to an HTTPS one.`
This reads a bit awkwardly, maybe something like 
`which is why an HTTP connection from a browser will switch to HTTPS.`
## Configuring the user registry
* `...and authorization using API` -> `and authorization using an API`
* The `Create UserRegistry configuration file` command says to create `UserRegistry` when the file is `userRegistry`. Potentially confusing casing.
* the `bob`, `alice`, `carl`,`dave` hotspots should probably point to their entries in the `<user/>` tags
* ~~I think it is worth explaining why it is bad to store plaintext passwords. Just a small blurb about how an attacker could see the passwords if the storage is compromised or something.~~
* the `server.xml` hotspot is weird, it points to the `<application-bnd/>` tag without sufficient context

**Comment by NimG98** [comment]
Being addressed in devmode PR.

Here's the commit: 
https://github.com/OpenLiberty/guide-security-intro/pull/97/commits/218bebc6de2b51396ddbafb3546f8f766a11d132
